name: sakamata
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    build:
      context: ./server
    environment:
      - CHANNEL_ID=$CHANNEL_ID
      - API_KEY=$API_KEY
    restart: always
  client:
    build:
      context: ./client
