# syntax=docker/dockerfile:1

FROM golang:1.20

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY main.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /go-server

EXPOSE 5000
CMD ["./go-server"]
